export enum EventType {
  // Connection
  CONNECTED = "CONNECTED",

  // Chat lifecycle
  CHAT_CHANGED = "CHAT_CHANGED",
  CHAT_SWITCHED = "CHAT_SWITCHED",
  CHAT_DELETED = "CHAT_DELETED",
  CHAT_FORKED = "CHAT_FORKED",
  MESSAGE_SENT = "MESSAGE_SENT",
  MESSAGE_EDITED = "MESSAGE_EDITED",
  MESSAGE_DELETED = "MESSAGE_DELETED",
  MESSAGE_SWIPED = "MESSAGE_SWIPED",
  SWIPE_EDITED = "SWIPE_EDITED",
  CHARACTER_MESSAGE_RENDERED = "CHARACTER_MESSAGE_RENDERED",
  USER_MESSAGE_RENDERED = "USER_MESSAGE_RENDERED",

  // Generation
  GENERATION_STARTED = "GENERATION_STARTED",
  GENERATION_ENDED = "GENERATION_ENDED",
  GENERATION_STOPPED = "GENERATION_STOPPED",
  GENERATION_ACKNOWLEDGED = "GENERATION_ACKNOWLEDGED",
  GENERATION_IN_PROGRESS = "GENERATION_IN_PROGRESS",
  GENERATION_PHASE_CHANGED = "GENERATION_PHASE_CHANGED",
  STREAM_TOKEN_RECEIVED = "STREAM_TOKEN_RECEIVED",

  // Entities
  CHARACTER_CREATED = "CHARACTER_CREATED",
  CHARACTER_EDITED = "CHARACTER_EDITED",
  CHARACTER_DELETED = "CHARACTER_DELETED",
  CHARACTER_DUPLICATED = "CHARACTER_DUPLICATED",
  PERSONA_CHANGED = "PERSONA_CHANGED",

  // Images
  IMAGE_UPLOADED = "IMAGE_UPLOADED",
  IMAGE_DELETED = "IMAGE_DELETED",

  // Settings
  SETTINGS_UPDATED = "SETTINGS_UPDATED",
  PRESET_CHANGED = "PRESET_CHANGED",
  PRESET_DELETED = "PRESET_DELETED",
  CONNECTION_PROFILE_LOADED = "CONNECTION_PROFILE_LOADED",
  MAIN_API_CHANGED = "MAIN_API_CHANGED",
  WORLD_INFO_ACTIVATED = "WORLD_INFO_ACTIVATED",

  // Preset Profiles
  PRESET_PROFILE_CHANGED = "PRESET_PROFILE_CHANGED",

  // Packs
  PACK_CHANGED = "PACK_CHANGED",
  PACK_DELETED = "PACK_DELETED",

  // Council
  COUNCIL_STARTED = "COUNCIL_STARTED",
  COUNCIL_MEMBER_DONE = "COUNCIL_MEMBER_DONE",
  COUNCIL_COMPLETED = "COUNCIL_COMPLETED",
  COUNCIL_TOOLS_FAILED = "COUNCIL_TOOLS_FAILED",

  WEAVER_VISUAL_JOB_CREATED = "WEAVER_VISUAL_JOB_CREATED",
  WEAVER_VISUAL_JOB_PROGRESS = "WEAVER_VISUAL_JOB_PROGRESS",
  WEAVER_VISUAL_JOB_COMPLETED = "WEAVER_VISUAL_JOB_COMPLETED",
  WEAVER_VISUAL_JOB_FAILED = "WEAVER_VISUAL_JOB_FAILED",

  // Spindle extension events
  SPINDLE_EXTENSION_LOADED = "SPINDLE_EXTENSION_LOADED",
  SPINDLE_EXTENSION_UNLOADED = "SPINDLE_EXTENSION_UNLOADED",
  SPINDLE_EXTENSION_ERROR = "SPINDLE_EXTENSION_ERROR",
  SPINDLE_EXTENSION_STATUS = "SPINDLE_EXTENSION_STATUS",
  SPINDLE_RUNTIME_STATS = "SPINDLE_RUNTIME_STATS",
  SPINDLE_PRE_GENERATION_ACTIVITY = "SPINDLE_PRE_GENERATION_ACTIVITY",
  SPINDLE_BULK_UPDATE_PROGRESS = "SPINDLE_BULK_UPDATE_PROGRESS",
  SPINDLE_BULK_UPDATE_COMPLETE = "SPINDLE_BULK_UPDATE_COMPLETE",
  SPINDLE_FRONTEND_MSG = "SPINDLE_FRONTEND_MSG",
  SPINDLE_FRONTEND_PROCESS = "SPINDLE_FRONTEND_PROCESS",
  SPINDLE_TOAST = "SPINDLE_TOAST",
  MESSAGE_TAG_INTERCEPTED = "MESSAGE_TAG_INTERCEPTED",

  // Spindle text editor
  SPINDLE_TEXT_EDITOR_OPEN = "SPINDLE_TEXT_EDITOR_OPEN",
  SPINDLE_TEXT_EDITOR_RESULT = "SPINDLE_TEXT_EDITOR_RESULT",

  // Spindle modal
  SPINDLE_MODAL_OPEN = "SPINDLE_MODAL_OPEN",
  SPINDLE_MODAL_RESULT = "SPINDLE_MODAL_RESULT",
  SPINDLE_CONFIRM_OPEN = "SPINDLE_CONFIRM_OPEN",
  SPINDLE_CONFIRM_RESULT = "SPINDLE_CONFIRM_RESULT",
  SPINDLE_INPUT_PROMPT_OPEN = "SPINDLE_INPUT_PROMPT_OPEN",
  SPINDLE_INPUT_PROMPT_RESULT = "SPINDLE_INPUT_PROMPT_RESULT",

  // Tool invocation (Spindle extension tools)
  TOOL_INVOCATION = "TOOL_INVOCATION",

  // Regex Scripts
  REGEX_SCRIPT_CHANGED = "REGEX_SCRIPT_CHANGED",
  REGEX_SCRIPT_DELETED = "REGEX_SCRIPT_DELETED",

  // World Books
  WORLD_BOOK_CHANGED = "WORLD_BOOK_CHANGED",
  WORLD_BOOK_DELETED = "WORLD_BOOK_DELETED",
  WORLD_BOOK_ENTRY_CHANGED = "WORLD_BOOK_ENTRY_CHANGED",
  WORLD_BOOK_ENTRY_DELETED = "WORLD_BOOK_ENTRY_DELETED",

  // Expressions
  EXPRESSION_CHANGED = "EXPRESSION_CHANGED",

  // Avatar
  CHARACTER_AVATAR_CHANGED = "CHARACTER_AVATAR_CHANGED",

  // Image Gen Connections
  IMAGE_GEN_CONNECTION_CHANGED = "IMAGE_GEN_CONNECTION_CHANGED",

  // Image Gen Streaming (Comfy/Swarm progress)
  IMAGE_GEN_PROGRESS = "IMAGE_GEN_PROGRESS",
  IMAGE_GEN_COMPLETE = "IMAGE_GEN_COMPLETE",
  IMAGE_GEN_ERROR = "IMAGE_GEN_ERROR",

  // TTS Connections
  TTS_CONNECTION_CHANGED = "TTS_CONNECTION_CHANGED",

  // STT Connections
  STT_CONNECTION_CHANGED = "STT_CONNECTION_CHANGED",

  // Theme overrides (Spindle extensions)
  SPINDLE_THEME_OVERRIDES = "SPINDLE_THEME_OVERRIDES",

  // Per-chat CSS containment mode (Spindle extensions, app_manipulation)
  SPINDLE_CHAT_STYLE_MODE = "SPINDLE_CHAT_STYLE_MODE",

  // Spindle permission changes (broadcast with extensionId so frontends can scope)
  SPINDLE_PERMISSION_CHANGED = "SPINDLE_PERMISSION_CHANGED",

  // Spindle command palette commands
  SPINDLE_COMMANDS_CHANGED = "SPINDLE_COMMANDS_CHANGED",

  // Spindle UI automation (navigate drawer/settings/command palette)
  SPINDLE_UI_NAVIGATE = "SPINDLE_UI_NAVIGATE",

  // Import progress
  IMPORT_GALLERY_PROGRESS = "IMPORT_GALLERY_PROGRESS",

  // User-data export/import (portability)
  USER_EXPORT_PROGRESS = "USER_EXPORT_PROGRESS",
  USER_IMPORT_PROGRESS = "USER_IMPORT_PROGRESS",
  USER_IMPORT_COMPLETE = "USER_IMPORT_COMPLETE",
  USER_IMPORT_FAILED = "USER_IMPORT_FAILED",

  // LumiHub remote install
  LUMIHUB_INSTALL_STARTED = "LUMIHUB_INSTALL_STARTED",
  LUMIHUB_INSTALL_COMPLETED = "LUMIHUB_INSTALL_COMPLETED",
  LUMIHUB_INSTALL_FAILED = "LUMIHUB_INSTALL_FAILED",
  LUMIHUB_CONNECTION_CHANGED = "LUMIHUB_CONNECTION_CHANGED",

  // SillyTavern Migration
  MIGRATION_PROGRESS = "MIGRATION_PROGRESS",
  MIGRATION_LOG = "MIGRATION_LOG",
  MIGRATION_COMPLETED = "MIGRATION_COMPLETED",
  MIGRATION_FAILED = "MIGRATION_FAILED",

  // Operator panel
  OPERATOR_LOG = "OPERATOR_LOG",
  OPERATOR_STATUS = "OPERATOR_STATUS",
  OPERATOR_PROGRESS = "OPERATOR_PROGRESS",

  // Memory Cortex
  CORTEX_REBUILD_PROGRESS = "CORTEX_REBUILD_PROGRESS",
  CORTEX_INGESTION_PROGRESS = "CORTEX_INGESTION_PROGRESS",
  CORTEX_VAULT_CREATED = "CORTEX_VAULT_CREATED",
  CORTEX_VAULT_REINDEXED = "CORTEX_VAULT_REINDEXED",
  CORTEX_LINK_CHANGED = "CORTEX_LINK_CHANGED",

  // MCP Servers
  MCP_SERVER_CONNECTED = "MCP_SERVER_CONNECTED",
  MCP_SERVER_DISCONNECTED = "MCP_SERVER_DISCONNECTED",
  MCP_SERVER_ERROR = "MCP_SERVER_ERROR",
  MCP_SERVER_CHANGED = "MCP_SERVER_CHANGED",

  // Databank
  DATABANK_CHANGED = "DATABANK_CHANGED",
  DATABANK_DELETED = "DATABANK_DELETED",
  DATABANK_DOCUMENT_STATUS = "DATABANK_DOCUMENT_STATUS",

  // Global Add-Ons
  GLOBAL_ADDON_CHANGED = "GLOBAL_ADDON_CHANGED",
  GLOBAL_ADDON_DELETED = "GLOBAL_ADDON_DELETED",

  // Loom summary auto-summarization
  SUMMARIZATION_STARTED = "SUMMARIZATION_STARTED",
  SUMMARIZATION_PROGRESS = "SUMMARIZATION_PROGRESS",
  SUMMARIZATION_COMPLETED = "SUMMARIZATION_COMPLETED",
  SUMMARIZATION_FAILED = "SUMMARIZATION_FAILED",

  // System health
  SYSTEM_DISK_LOW = "SYSTEM_DISK_LOW",
}

export interface EventMessage {
  event: EventType;
  payload: any;
  timestamp: number;
  userId?: string;
}
