import { getDb } from "../db/connection";
import * as settingsSvc from "../services/settings.service";

export const DEFAULT_PRESET_BLOCKS = [
  {
    id: "019e62a4-7dba-7001-a422-10836ade35dd",
    name: "System Prompt",
    content: "Write {{char}}'s next reply in a fictional roleplay chat between {{char}} and {{user}}.\n\nStay faithful to the Character Sheet above all else. Use the character description, personality, scenario, chat history, and example messages as grounding. If details are missing, infer carefully from context without contradicting established canon.\n\nWrite only the next response from {{char}}. Do not write {{user}}'s dialogue or decisions for them. You may describe {{user}} only when reacting to actions already established in the chat.\n\nKeep the scene moving. Each reply should respond to what just happened, preserve continuity, and offer something for {{user}} to answer or act on.",
    role: "system",
    enabled: true,
    position: "pre_history",
    depth: 0,
    marker: null,
    isLocked: false,
    color: null,
    injectionTrigger: [],
    categoryMode: null,
  },
  {
    id: "019e66ae-319a-7000-b72c-26f783bb909e",
    name: "Persona and scenario",
    content: "",
    role: "system",
    enabled: true,
    position: "pre_history",
    depth: 0,
    marker: "category",
    isLocked: false,
    color: null,
    injectionTrigger: [],
    categoryMode: null,
  },
  {
    id: "019e66ae-3e02-7000-8daf-de89a2d40f2e",
    name: "Scenario",
    content: "<scenario>\nCurrent scenario:\n{{scenario}}\n\nUse this as the active situation, setting, conflict, and relationship context. Treat it as more important than generic assumptions, but less important than the character's fixed definition.\n</scenario>",
    role: "system",
    enabled: true,
    position: "pre_history",
    depth: 0,
    marker: null,
    isLocked: false,
    color: null,
    injectionTrigger: [],
    categoryMode: null,
  },
  {
    id: "019e66ae-4710-7000-a5c3-51cfb3443d5e",
    name: "Character Description",
    content: "<description>\nCharacter being portrayed:\n{{description}}\n\nUse these details for appearance, background, abilities, limitations, relationships, and role in the story. Do not overwrite or ignore them.\n</description>",
    role: "system",
    enabled: true,
    position: "pre_history",
    depth: 0,
    marker: null,
    isLocked: false,
    color: null,
    injectionTrigger: [],
    categoryMode: null,
  },
  {
    id: "019e66ae-51cc-7000-8642-91469a1b1e5b",
    name: "Personality",
    content: "<personality>\n{{char}}'s personality:\n{{personality}}\n\nPreserve the character's emotional patterns, speech style, priorities, flaws, and boundaries. Let their behavior come from who they are, not from generic roleplay habits.\n</personality>",
    role: "system",
    enabled: true,
    position: "pre_history",
    depth: 0,
    marker: null,
    isLocked: false,
    color: null,
    injectionTrigger: [],
    categoryMode: null,
  },
  {
    id: "019e66ae-5926-7000-89b8-46d7411dc9f2",
    name: "User Persona",
    content: "<userpersona>\nUser persona:\n{{persona}}\n\nUse this only to understand who {{user}} is in the scene. React to {{user}}'s persona, but do not control their thoughts, speech, or choices.\n</userpersona>",
    role: "system",
    enabled: true,
    position: "pre_history",
    depth: 0,
    marker: null,
    isLocked: false,
    color: null,
    injectionTrigger: [],
    categoryMode: null,
  },
  {
    id: "019e62a4-7dba-7002-9d48-1b42dfcebb5a",
    name: "Chat History",
    content: "",
    role: "system",
    enabled: true,
    position: "pre_history",
    depth: 0,
    marker: "chat_history",
    isLocked: true,
    color: null,
    injectionTrigger: [],
    categoryMode: null,
  },
  {
    id: "019e66ae-5f21-7000-83e3-df7660b21c8e",
    name: "Example Messages",
    content: "<mesexamples>\nExample messages, if available:\n{{mesExamples}}\n\nFollow the character's voice, rhythm, and formatting shown here. Use examples as style guidance, not as events that necessarily happened in the current chat.\n</mesexamples>",
    role: "system",
    enabled: true,
    position: "pre_history",
    depth: 0,
    marker: null,
    isLocked: false,
    color: null,
    injectionTrigger: [],
    categoryMode: null,
  },
  {
    id: "019e67eb-1467-7000-a011-52c3124c1457",
    name: "Narrative drive",
    content: "",
    role: "system",
    enabled: true,
    position: "pre_history",
    depth: 0,
    marker: "category",
    isLocked: false,
    color: null,
    injectionTrigger: [],
    categoryMode: null,
  },
  {
    id: "019e67eb-5dd0-7000-b764-6cedc07fead2",
    name: "Narrative Guidance",
    content: "<narrative_guidance>\nWrite with the character's voice as the foundation of every reply. Word choice, rhythm, emotional expression, humor, restraint, and intensity should all feel shaped by who {{char}} is rather than by generic prose habits. Style is welcome, but it should serve the character and the scene instead of overpowering them.\n\nLet each response meaningfully react to what just happened. Show how {{char}} absorbs {{user}}'s words, actions, mood, or silence, then let that reaction influence what they say or do next. Avoid filler exchanges that only acknowledge the previous message without changing the emotional or narrative state of the scene.\n\nPreserve continuity carefully. Keep track of established facts, recent emotional beats, physical positioning, ongoing tension, relationship dynamics, and unresolved conflicts. New developments should feel like they grow from what came before, not like sudden twists added only to create drama.\n\nUse tension, affection, humor, vulnerability, distance, conflict, or tenderness when the scene naturally supports them. Let moments breathe instead of rushing to resolve them. If there is discomfort, attraction, suspicion, grief, anger, or intimacy in the scene, allow it to affect the pacing and behavior of the character.\n\nFavor showing over summarizing. Reveal emotion through action, dialogue, hesitation, posture, sensory detail, and subtext rather than explaining everything directly. Inner thought can be used when helpful, but it should not replace interaction or stall the scene inside excessive introspection.\n\nAvoid repeating the same emotional beat in different words. If {{char}} has already reacted with shock, guilt, teasing, denial, affection, or anger, let the next reply develop that reaction instead of circling it. Each message should add motion, pressure, clarity, complication, or a new choice.\n\nDo not resolve conflict too easily. Let misunderstandings, desire, fear, pride, loyalty, secrecy, or external pressure remain active when appropriate. Progress should feel earned through interaction, not handed over because the scene needs to move quickly.\n\nDo not speak, decide, emote, or act for {{user}} beyond what the chat has already established. Leave {{user}} room to respond, resist, interrupt, choose, or redirect. {{char}} may interpret {{user}} imperfectly, but should not define {{user}}'s inner thoughts or force their next action.\n</narrative_guidance>\n\n<response_shape>\nEach reply should usually include:\n1. a direct reaction to {{user}} or the latest event\n2. character-specific emotion, thought, or body language\n3. dialogue or action that moves the scene forward\n</response_shape>",
    role: "system",
    enabled: true,
    position: "pre_history",
    depth: 0,
    marker: null,
    isLocked: false,
    color: null,
    injectionTrigger: [],
    categoryMode: null,
  },
  {
    id: "019e67ec-456f-7000-bdca-508d420aec61",
    name: "OOC instructions",
    content: "<ooc>\nOOC instructions from the user may guide tone, pacing, formatting, or scene direction. Follow them unless they contradict the character sheet, scenario, or higher-priority instructions.\n\nIf the user gives a correction, treat it as updated direction for future replies.\n</ooc>",
    role: "system",
    enabled: true,
    position: "pre_history",
    depth: 0,
    marker: null,
    isLocked: false,
    color: null,
    injectionTrigger: [],
    categoryMode: null,
  },
  {
    id: "019e66ab-3948-7000-832e-7c2f5b8724dd",
    name: "Summaries",
    content: "",
    role: "system",
    enabled: true,
    position: "pre_history",
    depth: 0,
    marker: "category",
    isLocked: false,
    color: null,
    injectionTrigger: [],
    categoryMode: null,
  },
  {
    id: "019e66ab-16ed-7000-92eb-ef0a0cd16e5c",
    name: "Cortex",
    content: "<cortex>\n{{if {{cortexActive}} = yes}}\n{{entities}}\n{{relationships}}\n{{arc}}\n{{memorySalience}}\n{{/if}}\n</cortex>",
    role: "system",
    enabled: true,
    position: "pre_history",
    depth: 0,
    marker: null,
    isLocked: false,
    color: null,
    injectionTrigger: [],
    categoryMode: null,
  },
  {
    id: "019e66ab-654a-7000-9a19-89e794808c82",
    name: "Story Summary",
    content: "{{loomSummary}}",
    role: "system",
    enabled: true,
    position: "pre_history",
    depth: 0,
    marker: null,
    isLocked: false,
    color: null,
    injectionTrigger: [],
    categoryMode: null,
  },
  {
    id: "019e66ab-56a8-7000-8518-90ce012ad6cc",
    name: "Chat Memories",
    content: "{{memories}}",
    role: "system",
    enabled: true,
    position: "pre_history",
    depth: 0,
    marker: null,
    isLocked: false,
    color: null,
    injectionTrigger: [],
    categoryMode: null,
  },
  {
    id: "019e66ab-591a-7000-a8cd-d5d71c1cad15",
    name: "Loom",
    content: "",
    role: "system",
    enabled: true,
    position: "pre_history",
    depth: 0,
    marker: "category",
    isLocked: false,
    color: null,
    injectionTrigger: [],
    categoryMode: null,
  },
  {
    id: "019e6810-448b-7000-a38e-de92d06f881f",
    name: "Sovhand",
    content: "{{if {{loomSovHandActive}} = yes}}\n{{loomSovHand}}\n{{/if}}",
    role: "system",
    enabled: true,
    position: "pre_history",
    depth: 0,
    marker: null,
    isLocked: false,
    color: null,
    injectionTrigger: [],
    categoryMode: null,
  },
  {
    id: "019e66ab-923f-7000-94ec-f650dfce4423",
    name: "Loom Utilities",
    content: "<loomutilities>\n{{loomRetrofits}}\n{{loomUtils}}\n{{loomStyle}}\n</loomutilities>",
    role: "system",
    enabled: true,
    position: "pre_history",
    depth: 0,
    marker: null,
    isLocked: false,
    color: null,
    injectionTrigger: [],
    categoryMode: null,
  },
  {
    id: "019e67f5-6109-7000-9924-92ae3f9a696b",
    name: "Council",
    content: "{{if {{lumiaCouncilModeActive}} = yes}}\n{{lumiaCouncilInst}}\n{{lumiaCouncilDeliberation}}\n{{lumiaQuirks}}\n{{/if}}\n",
    role: "system",
    enabled: true,
    position: "pre_history",
    depth: 0,
    marker: null,
    isLocked: false,
    color: null,
    injectionTrigger: [],
    categoryMode: null,
  },
  {
    id: "019e66ab-b515-7000-b862-779d925785b8",
    name: "Lumia OOC",
    content: "<lumiaooc>\n{{lumiaOOC}}\n{{lumiaQuirks}}\n{{lumiaDef}}\n</lumiaooc>",
    role: "system",
    enabled: false,
    position: "pre_history",
    depth: 0,
    marker: null,
    isLocked: false,
    color: null,
    injectionTrigger: [],
    categoryMode: null,
  },
];

export const DEFAULT_PRESET_PARAMETERS = {
  samplerOverrides: {
    enabled: true,
    maxTokens: null,
    contextSize: null,
    temperature: null,
    topP: null,
    minP: null,
    topK: null,
    frequencyPenalty: null,
    presencePenalty: null,
    repetitionPenalty: null,
    streaming: true,
  },
  customBody: {
    enabled: false,
    rawJson: "{}",
  },
};

export const DEFAULT_PRESET_PROMPTS = {
  promptBehavior: {
    continueNudge: "[Continue your last message without repeating its original content.]",
    emptySendNudge: "[Write the next reply only as {{char}}.]",
    impersonationPrompt: "[Write your next reply from the point of view of {{user}}, using the chat history so far as a guideline for the writing style of {{user}}. Don't write as {{char}} or system. Don't describe actions of {{char}}.]",
    groupNudge: "[Write the next reply only as {{char}}.]",
    newChatPrompt: "[Start a new Chat]",
    newGroupChatPrompt: "[Start a new group chat. Group members: {{group}}]",
    sendIfEmpty: "",
  },
  completionSettings: {
    assistantPrefill: "",
    assistantImpersonation: "",
    continuePrefill: false,
    continuePostfix: " ",
    namesBehavior: 0,
    squashSystemMessages: false,
    useSystemPrompt: true,
    enableWebSearch: false,
    sendInlineMedia: true,
    enableFunctionCalling: true,
    includeUsage: false,
  },
  advancedSettings: {
    seed: -1,
    customStopStrings: [],
    collapseMessages: false,
  },
};

const DEFAULT_PRESET_METADATA = {
  source: null,
  modelProfiles: {},
  schemaVersion: 1,
  description: "",
  coverUrl: null,
  isDefault: true,
  lastProfileKey: null,
  promptVariables: {},
};

/**
 * Insert the built-in "Default" preset for a user if they have no presets yet.
 * Sets it as the active preset so new users can generate immediately.
 */
export function seedDefaultPreset(userId: string): void {
  const db = getDb();

  const row = db
    .query("SELECT COUNT(*) as count FROM presets WHERE user_id = ?")
    .get(userId) as { count: number } | null;
  if (row && row.count > 0) return;

  const id = crypto.randomUUID();
  const now = Math.floor(Date.now() / 1000);

  db.query(
    "INSERT INTO presets (id, name, provider, engine, parameters, prompt_order, prompts, metadata, user_id, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
  ).run(
    id,
    "Default",
    "loom",
    "classic",
    JSON.stringify(DEFAULT_PRESET_PARAMETERS),
    JSON.stringify(DEFAULT_PRESET_BLOCKS),
    JSON.stringify(DEFAULT_PRESET_PROMPTS),
    JSON.stringify(DEFAULT_PRESET_METADATA),
    userId,
    now,
    now,
  );

  settingsSvc.putSetting(userId, "activeLoomPresetId", id);
}
